Repository hackbysarthak03/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#4 added my profile
  index.html
Labels: hacktoberfest-approved

#7 Add hover and animated
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-approved

#8 Added hover feature
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-approved

#13 This is my first contribution.
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#12 new contibutor added
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#15 feat/Make profile photo circular in cards of contributors
  .vscode/settings.json
  CSS/index.css
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#14 Add new Contributor
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#23 updated the footer
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#27 Added some media queries
  CSS/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#28 Add CSS styling to Hero Section
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#18 added simple contribution
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#17 My first contribution
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 some major changes made to the site
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#46 Changed Github icons
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#57 Added My card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#59 chore: addded icons to footer links
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#56 Typewriter effect at Codex
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#61 added profile
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#58 Simple Contribution
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#47 Added link and name
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#62 added carasouel to the homepage
  img/1.avif
  img/2.avif
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#48 PR for name and github profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 Add new card in the website with name and github url
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#63 added contact form
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#67 enhancing submit button
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#70 Create Responsive Footer
  CSS/footer.css
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#68 Added Copyright
  CSS/index.css
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#81 Added my info in the index.html file
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#87 loader added
  .github/workflows/static.yml
  CSS/index.css
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#75 Added Name and Profile link to index.html
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#40 added new card in index.html
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted

#108 Added my name and GitHub in index.html file
  index.html
Labels: hacktoberfest, hacktoberfest-approved, hacktoberfest-accepted
